export const navItems = [
  { label: 'Home', href: '#home' },
  { label: 'Pets & Products', href: '#catalog' },
  { label: 'Details', href: '#details' },
  { label: 'Services', href: '#services' },
  { label: 'About', href: '#about' },
  { label: 'Contact', href: '#contact' },
];

export const catalogItems = [
  {
    id: 'dog',
    name: 'Bruno',
    category: 'Dog',
    kind: 'Adoption',
    price: 'Adoption fee: INR 2,500',
    age: '2 years',
    breed: 'Golden Retriever mix',
    care: 'Daily walks, brushing twice weekly, vaccination record included.',
    visual: 'visual-dog',
    image: '/images/dog.jpg',
    icon: '&#128021;',
    status: 'Ready for home visit',
  },
  {
    id: 'cat',
    name: 'Luna',
    category: 'Cat',
    kind: 'Adoption',
    price: 'Adoption fee: INR 1,800',
    age: '1 year',
    breed: 'Domestic short hair',
    care: 'Indoor home, litter trained, calm evening routine preferred.',
    visual: 'visual-cat',
    image: '/images/cat.jpg',
    icon: '&#128008;',
    status: 'Vaccinated',
  },
  {
    id: 'bird',
    name: 'Rio',
    category: 'Bird',
    kind: 'Adoption',
    price: 'Adoption fee: INR 1,200',
    age: '9 months',
    breed: 'Budgie',
    care: 'Social cage setup, fresh seed blend, gentle handling practice.',
    visual: 'visual-bird',
    image: '/images/bird.jpg',
    icon: '&#129436;',
    status: 'Hand trained',
  },
  {
    id: 'fish',
    name: 'Coral Pair',
    category: 'Fish',
    kind: 'Pet',
    price: 'INR 650',
    age: 'Young adult',
    breed: 'Guppy pair',
    care: 'Filtered tank, weekly water checks, peaceful community setup.',
    visual: 'visual-fish',
    image: '/images/fish.jpg',
    icon: '&#128032;',
    status: 'Starter friendly',
  },
  {
    id: 'rabbit',
    name: 'Mochi',
    category: 'Rabbit',
    kind: 'Adoption',
    price: 'Adoption fee: INR 1,500',
    age: '11 months',
    breed: 'Mini lop mix',
    care: 'Hay-rich diet, soft floor area, supervised playtime.',
    visual: 'visual-rabbit',
    image: '/images/rabbit.jpg',
    icon: '&#128007;',
    status: 'Gentle temperament',
  },
  {
    id: 'food',
    name: 'Balanced Pet Food',
    category: 'Food',
    kind: 'Product',
    price: 'From INR 399',
    age: 'All life stages',
    breed: 'Dogs, cats, birds, fish',
    care: 'Vet-guided nutrition packs with portion suggestions.',
    visual: 'visual-food',
    image: '/images/food.jpg',
    icon: '&#129368;',
    status: 'Best seller',
  },
  {
    id: 'toys',
    name: 'Play & Enrichment Toys',
    category: 'Toys',
    kind: 'Product',
    price: 'From INR 149',
    age: 'All ages',
    breed: 'Multi-pet range',
    care: 'Chew-safe, puzzle, feather, rope, and activity toys.',
    visual: 'visual-toys',
    image: '/images/toys.jpg',
    icon: '&#127922;',
    status: 'New arrivals',
  },
  {
    id: 'accessories',
    name: 'Comfort Accessories',
    category: 'Accessories',
    kind: 'Product',
    price: 'From INR 249',
    age: 'All ages',
    breed: 'Beds, bowls, leashes, tanks',
    care: 'Durable daily essentials selected by our care team.',
    visual: 'visual-accessories',
    image: '/images/accessories.jpg',
    icon: '&#127968;',
    status: 'In stock',
  },
];

export const categoryOptions = {
  dog: [
    {
      id: 'golden-retriever',
      title: 'Golden Retriever',
      subtitle: 'Friendly family companion',
      price: 'Adoption guidance from INR 2,500',
      age: 'Puppy to adult',
      bestFor: 'Active families, first-time pet parents, children',
      traits: ['Gentle', 'Social', 'Trainable'],
      description:
        'Golden Retrievers are warm, intelligent dogs who enjoy human company, regular exercise, and structured play.',
      care:
        'Plan daily walks, weekly brushing, basic obedience practice, and regular ear checks.',
      related: ['Starter leash set', 'High-protein food', 'Grooming package'],
      visual: 'visual-dog',
      image: '/images/breeds/golden-retriever.jpg',
      icon: '&#128021;',
    },
    {
      id: 'beagle',
      title: 'Beagle',
      subtitle: 'Curious small hound',
      price: 'Adoption guidance from INR 2,200',
      age: 'Young adult',
      bestFor: 'Homes that enjoy walks and scent games',
      traits: ['Playful', 'Food motivated', 'Compact'],
      description:
        'Beagles are cheerful, nose-led companions with a lively personality and a love for puzzle toys.',
      care:
        'Use secure walks, measured meals, scent enrichment, and patient recall training.',
      related: ['Puzzle feeder', 'Harness', 'Training treats'],
      visual: 'visual-dog',
      image: '/images/breeds/beagle.jpg',
      icon: '&#128021;',
    },
    {
      id: 'indie-dog',
      title: 'Indian Pariah',
      subtitle: 'Smart native breed',
      price: 'Adoption guidance from INR 1,500',
      age: 'All ages',
      bestFor: 'Indian climate, apartments, independent learners',
      traits: ['Hardy', 'Alert', 'Low grooming'],
      description:
        'Indian Pariah dogs are resilient, loyal, and well suited to local weather with thoughtful socialization.',
      care:
        'Focus on social walks, positive training, balanced food, and vaccination routines.',
      related: ['Vaccination plan', 'Cooling mat', 'Daily food pack'],
      visual: 'visual-dog',
      image: '/images/breeds/indian-pariah.jpg',
      icon: '&#128021;',
    },
    {
      id: 'labrador',
      title: 'Labrador Retriever',
      subtitle: 'Loyal active companion',
      price: 'Adoption guidance from INR 2,600',
      age: 'Puppy to senior',
      bestFor: 'Families, runners, playful homes',
      traits: ['Loyal', 'Energetic', 'Friendly'],
      description:
        'Labradors are cheerful, sturdy dogs who enjoy games, swimming, structured exercise, and close family time.',
      care:
        'Use daily exercise, measured meals, joint support, brushing, and positive reward training.',
      related: ['Fetch toy', 'Large bowl', 'Joint support food'],
      visual: 'visual-dog',
      image: '/images/breeds/labrador.jpg',
      icon: '&#128021;',
    },
    {
      id: 'german-shepherd',
      title: 'German Shepherd',
      subtitle: 'Confident working breed',
      price: 'Adoption guidance from INR 3,200',
      age: 'Young adult',
      bestFor: 'Experienced homes and training-focused owners',
      traits: ['Brave', 'Smart', 'Protective'],
      description:
        'German Shepherds are intelligent, devoted dogs who thrive with training, clear routines, and mental work.',
      care:
        'Plan obedience training, controlled socialization, coat brushing, and active daily walks.',
      related: ['Training leash', 'Puzzle toy', 'Grooming rake'],
      visual: 'visual-dog',
      image: '/images/breeds/german-shepherd.jpg',
      icon: '&#128021;',
    },
  ],
  cat: [
    {
      id: 'persian',
      title: 'Persian Cat',
      subtitle: 'Calm long-hair companion',
      price: 'Adoption guidance from INR 2,000',
      age: 'Kitten to adult',
      bestFor: 'Quiet indoor homes',
      traits: ['Calm', 'Affectionate', 'Grooming needs'],
      description:
        'Persian cats are gentle indoor companions with plush coats and a peaceful daily rhythm.',
      care:
        'Brush frequently, keep eyes clean, use quality litter, and offer soft resting spaces.',
      related: ['Slicker brush', 'Premium litter', 'Cozy bed'],
      visual: 'visual-cat',
      image: '/images/breeds/persian-cat.jpg',
      icon: '&#128008;',
    },
    {
      id: 'domestic-short-hair',
      title: 'Domestic Short Hair',
      subtitle: 'Adaptable city cat',
      price: 'Adoption guidance from INR 1,200',
      age: 'All ages',
      bestFor: 'Apartments, busy homes, new cat parents',
      traits: ['Adaptable', 'Low grooming', 'Playful'],
      description:
        'Domestic short hair cats are varied, hardy, and easy to care for with a loving indoor setup.',
      care:
        'Provide scratching posts, litter hygiene, interactive play, and routine vet checks.',
      related: ['Scratch tower', 'Wand toy', 'Litter box kit'],
      visual: 'visual-cat',
      image: '/images/breeds/domestic-short-hair.jpg',
      icon: '&#128008;',
    },
    {
      id: 'siamese',
      title: 'Siamese',
      subtitle: 'Talkative social cat',
      price: 'Adoption guidance from INR 2,800',
      age: 'Young adult',
      bestFor: 'People who want an interactive pet',
      traits: ['Vocal', 'Social', 'Smart'],
      description:
        'Siamese cats are expressive, people-focused, and happiest when they have company and mental games.',
      care:
        'Offer climbing space, daily play, puzzle feeders, and a predictable routine.',
      related: ['Cat tree', 'Puzzle feeder', 'Feather toy'],
      visual: 'visual-cat',
      image: '/images/breeds/siamese-cat.jpg',
      icon: '&#128008;',
    },
    {
      id: 'maine-coon',
      title: 'Maine Coon',
      subtitle: 'Large gentle house cat',
      price: 'Adoption guidance from INR 3,200',
      age: 'Kitten to adult',
      bestFor: 'Homes with space and grooming time',
      traits: ['Large', 'Gentle', 'Fluffy'],
      description:
        'Maine Coons are large, affectionate cats with soft personalities and impressive coats.',
      care:
        'Brush several times weekly, offer sturdy climbing spaces, and keep nutrition portioned.',
      related: ['Large cat tree', 'Wide litter tray', 'Deshedding comb'],
      visual: 'visual-cat',
      image: '/images/breeds/maine-coon.jpg',
      icon: '&#128008;',
    },
    {
      id: 'bengal',
      title: 'Bengal Cat',
      subtitle: 'Athletic spotted companion',
      price: 'Adoption guidance from INR 3,500',
      age: 'Young adult',
      bestFor: 'Interactive homes and enrichment lovers',
      traits: ['Athletic', 'Curious', 'Bold'],
      description:
        'Bengals are energetic, patterned cats who need play, climbing, and puzzle-based activity.',
      care:
        'Provide vertical space, daily chase games, food puzzles, and secure indoor routines.',
      related: ['Wall shelves', 'Puzzle feeder', 'Interactive ball'],
      visual: 'visual-cat',
      image: '/images/breeds/bengal-cat.jpg',
      icon: '&#128008;',
    },
  ],
  bird: [
    {
      id: 'budgie',
      title: 'Budgie',
      subtitle: 'Small cheerful companion',
      price: 'From INR 1,200',
      age: 'Young to adult',
      bestFor: 'Beginner bird keepers',
      traits: ['Social', 'Small space', 'Trainable'],
      description:
        'Budgies are bright, social birds that enjoy gentle handling, toys, and a clean cage setup.',
      care:
        'Use a spacious cage, fresh seed mix, leafy greens, and daily supervised interaction.',
      related: ['Starter cage', 'Seed blend', 'Swing toy'],
      visual: 'visual-bird',
      image: '/images/breeds/budgie.jpg',
      icon: '&#129436;',
    },
    {
      id: 'cockatiel',
      title: 'Cockatiel',
      subtitle: 'Gentle whistling bird',
      price: 'From INR 4,500',
      age: 'Young adult',
      bestFor: 'Homes with daily interaction time',
      traits: ['Gentle', 'Whistling', 'Bonding'],
      description:
        'Cockatiels are affectionate birds known for soft calls, crest expressions, and steady bonding.',
      care:
        'Provide varied perches, pellets, seed treats, bath access, and calm handling.',
      related: ['Pellet diet', 'Natural perches', 'Bath bowl'],
      visual: 'visual-bird',
      image: '/images/breeds/cockatiel.jpg',
      icon: '&#129436;',
    },
    {
      id: 'lovebird',
      title: 'Lovebird',
      subtitle: 'Colorful energetic pair',
      price: 'From INR 3,000',
      age: 'Young pair',
      bestFor: 'Experienced keepers or pair setups',
      traits: ['Energetic', 'Colorful', 'Pair friendly'],
      description:
        'Lovebirds bring color and movement, and do best with enrichment, safe toys, and patient handling.',
      care:
        'Use chew-safe toys, fresh vegetables, flight time, and careful socialization.',
      related: ['Chew toys', 'Vegetable clips', 'Flight cage'],
      visual: 'visual-bird',
      image: '/images/breeds/lovebird.jpg',
      icon: '&#129436;',
    },
    {
      id: 'african-grey',
      title: 'African Grey',
      subtitle: 'Highly intelligent parrot',
      price: 'From INR 18,000',
      age: 'Juvenile to adult',
      bestFor: 'Experienced bird keepers',
      traits: ['Smart', 'Talkative', 'Sensitive'],
      description:
        'African Greys are brilliant parrots that need patient handling, enrichment, and a calm home.',
      care:
        'Use foraging toys, varied diet, daily interaction, and consistent sleep routines.',
      related: ['Foraging box', 'Pellet diet', 'Training perch'],
      visual: 'visual-bird',
      image: '/images/breeds/african-grey.jpg',
      icon: '&#129436;',
    },
    {
      id: 'zebra-finch',
      title: 'Zebra Finch',
      subtitle: 'Tiny active songbird',
      price: 'From INR 900',
      age: 'Young pair',
      bestFor: 'Pair aviaries and gentle observation',
      traits: ['Tiny', 'Active', 'Pair friendly'],
      description:
        'Zebra Finches are lively little birds that bring soft song and movement to a clean cage setup.',
      care:
        'Keep pairs, provide flight space, seed mix, greens, and a quiet sleeping area.',
      related: ['Finch cage', 'Millet spray', 'Nest cup'],
      visual: 'visual-bird',
      image: '/images/breeds/zebra-finch.jpg',
      icon: '&#129436;',
    },
  ],
  fish: [
    {
      id: 'guppy',
      title: 'Guppy',
      subtitle: 'Colorful starter fish',
      price: 'From INR 150',
      age: 'Young adult',
      bestFor: 'Community tanks and beginners',
      traits: ['Colorful', 'Peaceful', 'Starter friendly'],
      description:
        'Guppies are active, colorful freshwater fish that thrive in peaceful planted aquariums.',
      care:
        'Keep stable water, gentle filtration, weekly checks, and small measured feedings.',
      related: ['Water test kit', 'Micro pellets', 'Aquarium plants'],
      visual: 'visual-fish',
      image: '/images/breeds/guppy.jpg',
      icon: '&#128032;',
    },
    {
      id: 'betta',
      title: 'Betta',
      subtitle: 'Elegant solo fish',
      price: 'From INR 350',
      age: 'Adult',
      bestFor: 'Single-species display tanks',
      traits: ['Vibrant', 'Solo setup', 'Low current'],
      description:
        'Bettas are striking fish that prefer calm water, warm temperatures, and carefully chosen tank mates.',
      care:
        'Use a heater, low-flow filter, hiding plants, and avoid keeping two males together.',
      related: ['Heater', 'Silk plants', 'Betta food'],
      visual: 'visual-fish',
      image: '/images/breeds/betta.jpg',
      icon: '&#128032;',
    },
    {
      id: 'goldfish',
      title: 'Goldfish',
      subtitle: 'Classic cold-water fish',
      price: 'From INR 250',
      age: 'Juvenile',
      bestFor: 'Larger filtered tanks',
      traits: ['Hardy', 'Visible', 'Long lived'],
      description:
        'Goldfish are hardy and charming, but need more space and filtration than many new keepers expect.',
      care:
        'Choose a roomy tank, strong filtration, weekly water changes, and quality sinking food.',
      related: ['Large filter', 'Sinking pellets', 'Gravel cleaner'],
      visual: 'visual-fish',
      image: '/images/breeds/goldfish.jpg',
      icon: '&#128032;',
    },
    {
      id: 'angelfish',
      title: 'Angelfish',
      subtitle: 'Elegant tall-fin fish',
      price: 'From INR 450',
      age: 'Juvenile to adult',
      bestFor: 'Tall peaceful aquariums',
      traits: ['Graceful', 'Tall tank', 'Semi-peaceful'],
      description:
        'Angelfish add height and movement to freshwater tanks with their distinct shape and calm glide.',
      care:
        'Use a tall tank, warm stable water, gentle tank mates, and quality flakes or pellets.',
      related: ['Tall plants', 'Heater', 'Premium flakes'],
      visual: 'visual-fish',
      image: '/images/breeds/angelfish.jpg',
      icon: '&#128032;',
    },
    {
      id: 'molly',
      title: 'Molly',
      subtitle: 'Peaceful community fish',
      price: 'From INR 180',
      age: 'Young adult',
      bestFor: 'Beginner community tanks',
      traits: ['Peaceful', 'Hardy', 'Social'],
      description:
        'Mollies are hardy community fish that enjoy groups, plant cover, and clean stable water.',
      care:
        'Keep gentle filtration, vegetable-based food, stable temperature, and weekly water checks.',
      related: ['Vegetable flakes', 'Live plants', 'Water conditioner'],
      visual: 'visual-fish',
      image: '/images/breeds/molly.jpg',
      icon: '&#128032;',
    },
  ],
  rabbit: [
    {
      id: 'mini-lop',
      title: 'Mini Lop',
      subtitle: 'Soft compact rabbit',
      price: 'Adoption guidance from INR 1,500',
      age: 'Young adult',
      bestFor: 'Indoor homes with floor time',
      traits: ['Gentle', 'Compact', 'Hay focused'],
      description:
        'Mini lops are sweet, soft-eared rabbits who enjoy calm handling and safe indoor play.',
      care:
        'Offer unlimited hay, a roomy pen, soft flooring, nail trims, and supervised exercise.',
      related: ['Timothy hay', 'Exercise pen', 'Ceramic bowl'],
      visual: 'visual-rabbit',
      image: '/images/breeds/mini-lop.jpg',
      icon: '&#128007;',
    },
    {
      id: 'dutch-rabbit',
      title: 'Dutch Rabbit',
      subtitle: 'Friendly patterned rabbit',
      price: 'Adoption guidance from INR 1,700',
      age: 'All ages',
      bestFor: 'Families who can supervise gently',
      traits: ['Friendly', 'Curious', 'Neat size'],
      description:
        'Dutch rabbits are alert and personable with a classic pattern and an energetic routine.',
      care:
        'Provide chew toys, hay, leafy greens, litter training, and safe hiding spaces.',
      related: ['Rabbit litter tray', 'Chew sticks', 'Leafy greens pack'],
      visual: 'visual-rabbit',
      image: '/images/breeds/dutch-rabbit.jpg',
      icon: '&#128007;',
    },
    {
      id: 'lionhead',
      title: 'Lionhead',
      subtitle: 'Tiny rabbit with a mane',
      price: 'Adoption guidance from INR 2,000',
      age: 'Young adult',
      bestFor: 'Owners ready for coat care',
      traits: ['Small', 'Expressive', 'Grooming needs'],
      description:
        'Lionheads are compact rabbits with distinctive fluffy coats and plenty of personality.',
      care:
        'Brush the mane, keep nails trimmed, maintain hay intake, and prevent heat stress.',
      related: ['Soft brush', 'Cooling mat', 'Hay rack'],
      visual: 'visual-rabbit',
      image: '/images/breeds/lionhead-rabbit.jpg',
      icon: '&#128007;',
    },
    {
      id: 'rex-rabbit',
      title: 'Rex Rabbit',
      subtitle: 'Velvety gentle rabbit',
      price: 'Adoption guidance from INR 1,900',
      age: 'Young adult',
      bestFor: 'Indoor homes with calm routines',
      traits: ['Velvety', 'Gentle', 'Medium size'],
      description:
        'Rex rabbits are known for their plush coat, steady temperament, and friendly indoor nature.',
      care:
        'Use soft flooring, hay-rich meals, weekly checks, and supervised free-roam time.',
      related: ['Soft mat', 'Hay feeder', 'Grooming glove'],
      visual: 'visual-rabbit',
      image: '/images/breeds/rex-rabbit.jpg',
      icon: '&#128007;',
    },
    {
      id: 'himalayan-rabbit',
      title: 'Himalayan Rabbit',
      subtitle: 'Calm pointed rabbit',
      price: 'Adoption guidance from INR 2,100',
      age: 'All ages',
      bestFor: 'Families wanting a calm rabbit',
      traits: ['Calm', 'Lightweight', 'Distinct markings'],
      description:
        'Himalayan rabbits are calm, elegant rabbits with pointed markings and a gentle handling style.',
      care:
        'Provide shade, hay, fresh greens, litter training, and gentle daily handling.',
      related: ['Cooling tile', 'Litter tray', 'Fresh greens pack'],
      visual: 'visual-rabbit',
      image: '/images/breeds/himalayan-rabbit.jpg',
      icon: '&#128007;',
    },
  ],
  food: [
    {
      id: 'dog-cat-kibble',
      title: 'Dog & Cat Kibble',
      subtitle: 'Balanced daily nutrition',
      price: 'From INR 399',
      age: 'Puppy, kitten, adult, senior',
      bestFor: 'Daily complete meals',
      traits: ['Vet guided', 'Portion support', 'Life-stage options'],
      description:
        'Balanced kibble packs support everyday nutrition with protein, fiber, and clear portion guidance.',
      care:
        'Choose by age, size, activity, and sensitivity. Transition gradually over one week.',
      related: ['Measuring scoop', 'Slow feeder', 'Treat pouch'],
      visual: 'visual-food',
      image: '/images/breeds/dog-cat-kibble.jpg',
      icon: '&#129368;',
    },
    {
      id: 'bird-seed-mix',
      title: 'Bird Seed Mix',
      subtitle: 'Fresh daily blend',
      price: 'From INR 249',
      age: 'Small to medium birds',
      bestFor: 'Budgies, cockatiels, lovebirds',
      traits: ['Fresh', 'Clean blend', 'Easy feeding'],
      description:
        'A clean seed mix for small birds, best paired with greens and mineral support.',
      care:
        'Refresh daily, remove husks, add vegetables, and keep water clean.',
      related: ['Cuttlebone', 'Veg clip', 'Seed cup'],
      visual: 'visual-food',
      image: '/images/breeds/bird-seed-mix.jpg',
      icon: '&#129368;',
    },
    {
      id: 'fish-flakes',
      title: 'Fish Flakes & Pellets',
      subtitle: 'Aquarium feeding essentials',
      price: 'From INR 149',
      age: 'Most freshwater fish',
      bestFor: 'Community aquariums',
      traits: ['Easy dose', 'Floating', 'Daily feed'],
      description:
        'Staple flakes and pellets support colorful, active freshwater fish when used in small portions.',
      care:
        'Feed only what fish finish quickly and remove excess to protect water quality.',
      related: ['Auto feeder', 'Water conditioner', 'Test strips'],
      visual: 'visual-food',
      image: '/images/breeds/fish-flakes.jpg',
      icon: '&#129368;',
    },
    {
      id: 'wet-food',
      title: 'Wet Food Pouches',
      subtitle: 'Hydrating meal topper',
      price: 'From INR 79',
      age: 'Cats and dogs',
      bestFor: 'Picky eaters and hydration support',
      traits: ['Hydrating', 'Palatable', 'Portioned'],
      description:
        'Wet food pouches add moisture and aroma to meals, helping pets who need softer textures.',
      care:
        'Refrigerate opened packs, serve fresh, and balance with complete daily nutrition.',
      related: ['Food mat', 'Storage lids', 'Dental chews'],
      visual: 'visual-food',
      image: '/images/breeds/wet-food.jpg',
      icon: '&#129368;',
    },
    {
      id: 'rabbit-hay',
      title: 'Timothy Hay',
      subtitle: 'Essential rabbit fiber',
      price: 'From INR 299',
      age: 'Rabbits and guinea pigs',
      bestFor: 'Daily digestion and dental wear',
      traits: ['High fiber', 'Fresh', 'Daily staple'],
      description:
        'Timothy hay supports rabbit digestion and keeps teeth naturally worn through constant grazing.',
      care:
        'Offer unlimited hay, store dry, and refresh the rack every day.',
      related: ['Hay rack', 'Pellets', 'Ceramic bowl'],
      visual: 'visual-food',
      image: '/images/breeds/rabbit-hay.jpg',
      icon: '&#129368;',
    },
  ],
  toys: [
    {
      id: 'chew-toys',
      title: 'Chew Toys',
      subtitle: 'Safe chewing and teething',
      price: 'From INR 149',
      age: 'Puppies and adult dogs',
      bestFor: 'Chewers, teething pets, boredom control',
      traits: ['Durable', 'Chew-safe', 'Washable'],
      description:
        'Chew toys redirect chewing, support dental habits, and keep active pets occupied.',
      care:
        'Match toy size to pet strength and replace when worn or cracked.',
      related: ['Treats', 'Rope toy', 'Dental care kit'],
      visual: 'visual-toys',
      image: '/images/breeds/chew-toys.jpg',
      icon: '&#127922;',
    },
    {
      id: 'feather-wands',
      title: 'Feather Wands',
      subtitle: 'Interactive cat play',
      price: 'From INR 199',
      age: 'Cats of all ages',
      bestFor: 'Indoor exercise and hunting play',
      traits: ['Interactive', 'Lightweight', 'Energy burn'],
      description:
        'Feather wands help indoor cats jump, chase, and bond through short play sessions.',
      care:
        'Store after play, rotate toys, and avoid leaving strings unattended.',
      related: ['Scratch post', 'Cat tunnel', 'Treats'],
      visual: 'visual-toys',
      image: '/images/breeds/feather-wands.jpg',
      icon: '&#127922;',
    },
    {
      id: 'puzzle-feeders',
      title: 'Puzzle Feeders',
      subtitle: 'Mental enrichment tools',
      price: 'From INR 349',
      age: 'Dogs and cats',
      bestFor: 'Fast eaters and smart pets',
      traits: ['Enrichment', 'Slow feeding', 'Reusable'],
      description:
        'Puzzle feeders turn meals into activity and help pets use their brain while eating slowly.',
      care:
        'Start easy, increase difficulty gradually, and clean after sticky food.',
      related: ['Training treats', 'Slow bowl', 'Clicker'],
      visual: 'visual-toys',
      image: '/images/breeds/puzzle-feeders.jpg',
      icon: '&#127922;',
    },
    {
      id: 'rope-toys',
      title: 'Rope Toys',
      subtitle: 'Tug and chew play',
      price: 'From INR 199',
      age: 'Dogs of most sizes',
      bestFor: 'Tug games and supervised chewing',
      traits: ['Tug play', 'Durable', 'Dental texture'],
      description:
        'Rope toys are useful for supervised tug, fetch, and gentle chewing with active dogs.',
      care:
        'Choose the right size, wash regularly, and replace frayed ropes.',
      related: ['Training treats', 'Ball launcher', 'Chew toy'],
      visual: 'visual-toys',
      image: '/images/breeds/rope-toys.jpg',
      icon: '&#127922;',
    },
    {
      id: 'bird-toys',
      title: 'Bird Activity Toys',
      subtitle: 'Perches, swings, and shredders',
      price: 'From INR 249',
      age: 'Small and medium birds',
      bestFor: 'Daily enrichment and beak activity',
      traits: ['Colorful', 'Foraging', 'Chew-safe'],
      description:
        'Bird toys encourage movement, chewing, and curiosity so companion birds stay engaged.',
      care:
        'Rotate weekly, inspect for wear, and use bird-safe materials only.',
      related: ['Natural perch', 'Seed treats', 'Cage clips'],
      visual: 'visual-toys',
      image: '/images/breeds/bird-toys.jpg',
      icon: '&#127922;',
    },
  ],
  accessories: [
    {
      id: 'beds',
      title: 'Beds & Mats',
      subtitle: 'Daily comfort zone',
      price: 'From INR 499',
      age: 'All pets',
      bestFor: 'Rest, crate comfort, senior support',
      traits: ['Soft', 'Washable', 'Size options'],
      description:
        'Comfortable beds give pets a predictable rest space and protect them from hard flooring.',
      care:
        'Choose washable covers, correct size, and place away from strong heat or drafts.',
      related: ['Blanket', 'Cooling mat', 'Calming spray'],
      visual: 'visual-accessories',
      image: '/images/breeds/beds.jpg',
      icon: '&#127968;',
    },
    {
      id: 'leashes-harnesses',
      title: 'Leashes & Harnesses',
      subtitle: 'Secure walking gear',
      price: 'From INR 299',
      age: 'Dogs and walk-trained cats',
      bestFor: 'Daily walks and training',
      traits: ['Secure', 'Adjustable', 'Everyday use'],
      description:
        'A well-fitted harness improves control and comfort during walks, training, and travel.',
      care:
        'Measure chest size, check clips often, and avoid loose fits.',
      related: ['ID tag', 'Treat pouch', 'Poop bags'],
      visual: 'visual-accessories',
      image: '/images/breeds/leashes-harnesses.jpg',
      icon: '&#127968;',
    },
    {
      id: 'aquarium-kits',
      title: 'Aquarium Kits',
      subtitle: 'Starter tank essentials',
      price: 'From INR 1,499',
      age: 'Freshwater fish setups',
      bestFor: 'New aquarium keepers',
      traits: ['Filtered', 'Starter ready', 'Expandable'],
      description:
        'Starter aquarium kits simplify setup with tank, filter, lighting, and basic care essentials.',
      care:
        'Cycle the tank before adding fish, test water, and avoid overcrowding.',
      related: ['Water conditioner', 'Gravel', 'Plants'],
      visual: 'visual-accessories',
      image: '/images/breeds/aquarium-kits.jpg',
      icon: '&#127968;',
    },
    {
      id: 'grooming-tools',
      title: 'Grooming Tools',
      subtitle: 'Brushes, combs, and trimmers',
      price: 'From INR 299',
      age: 'Dogs, cats, and rabbits',
      bestFor: 'Coat care and hygiene routines',
      traits: ['Daily care', 'Comfort grip', 'Coat safe'],
      description:
        'Grooming tools make brushing, detangling, nail care, and coat maintenance easier at home.',
      care:
        'Pick tools by coat type, clean after use, and keep sessions short and gentle.',
      related: ['Shampoo', 'Towel', 'Nail clipper'],
      visual: 'visual-accessories',
      image: '/images/breeds/grooming-tools.jpg',
      icon: '&#127968;',
    },
    {
      id: 'pet-carriers',
      title: 'Pet Carriers',
      subtitle: 'Travel and vet visit support',
      price: 'From INR 899',
      age: 'Cats, small dogs, rabbits, birds',
      bestFor: 'Safe transport and short trips',
      traits: ['Ventilated', 'Secure', 'Travel ready'],
      description:
        'Pet carriers keep small pets secure and calm during vet visits, travel, and short transfers.',
      care:
        'Choose proper size, add a soft liner, and let pets explore it before travel.',
      related: ['Travel bowl', 'ID tag', 'Comfort liner'],
      visual: 'visual-accessories',
      image: '/images/breeds/pet-carriers.jpg',
      icon: '&#127968;',
    },
  ],
};

export const services = [
  {
    title: 'Grooming Studio',
    text: 'Bathing, trimming, nail care, coat conditioning, and hygiene packages.',
    icon: '&#9986;',
  },
  {
    title: 'Vet Support',
    text: 'Vaccination guidance, diet review, deworming reminders, and health records.',
    icon: '&#129658;',
  },
  {
    title: 'Boarding',
    text: 'Clean supervised stays with feeding plans, play sessions, and daily updates.',
    icon: '&#127968;',
  },
  {
    title: 'Training',
    text: 'Basic obedience, leash manners, socialization, and home settling support.',
    icon: '&#127891;',
  },
  {
    title: 'Delivery',
    text: 'Same-day delivery for food, toys, litter, aquariums, and care supplies.',
    icon: '&#128666;',
  },
  {
    title: 'Adoption Help',
    text: 'Matching, home checks, starter kits, and post-adoption follow-up calls.',
    icon: '&#128062;',
  },
];

export const trustBadges = [
  'Certified pet care advisors',
  'Vaccination records checked',
  'Clean grooming stations',
  'Transparent adoption process',
];

export const stats = [
  { value: '1.2k+', label: 'Happy adoptions' },
  { value: '4.9/5', label: 'Customer rating' },
  { value: '24/7', label: 'Care support' },
];
