export const navItems = [
  { label: 'Home', href: '#home' },
  { label: 'Pets & Products', href: '#catalog' },
  { label: 'Details', href: '#details' },
  { label: 'Services', href: '#services' },
  { label: 'About', href: '#about' },
  { label: 'Contact', href: '#contact' },
];

export const catalogItems = [
  {
    id: 'dog',
    name: 'Bruno',
    category: 'Dog',
    kind: 'Adoption',
    price: 'Adoption fee: INR 2,500',
    age: '2 years',
    breed: 'Golden Retriever mix',
    care: 'Daily walks, brushing twice weekly, vaccination record included.',
    visual: 'visual-dog',
    image: '/images/dog.jpg',
    icon: '&#128021;',
    status: 'Ready for home visit',
  },
  {
    id: 'cat',
    name: 'Luna',
    category: 'Cat',
    kind: 'Adoption',
    price: 'Adoption fee: INR 1,800',
    age: '1 year',
    breed: 'Domestic short hair',
    care: 'Indoor home, litter trained, calm evening routine preferred.',
    visual: 'visual-cat',
    image: '/images/cat.jpg',
    icon: '&#128008;',
    status: 'Vaccinated',
  },
  {
    id: 'bird',
    name: 'Rio',
    category: 'Bird',
    kind: 'Adoption',
    price: 'Adoption fee: INR 1,200',
    age: '9 months',
    breed: 'Budgie',
    care: 'Social cage setup, fresh seed blend, gentle handling practice.',
    visual: 'visual-bird',
    image: '/images/bird.jpg',
    icon: '&#129436;',
    status: 'Hand trained',
  },
  {
    id: 'fish',
    name: 'Coral Pair',
    category: 'Fish',
    kind: 'Pet',
    price: 'INR 650',
    age: 'Young adult',
    breed: 'Guppy pair',
    care: 'Filtered tank, weekly water checks, peaceful community setup.',
    visual: 'visual-fish',
    image: '/images/fish.jpg',
    icon: '&#128032;',
    status: 'Starter friendly',
  },
  {
    id: 'rabbit',
    name: 'Mochi',
    category: 'Rabbit',
    kind: 'Adoption',
    price: 'Adoption fee: INR 1,500',
    age: '11 months',
    breed: 'Mini lop mix',
    care: 'Hay-rich diet, soft floor area, supervised playtime.',
    visual: 'visual-rabbit',
    image: '/images/rabbit.jpg',
    icon: '&#128007;',
    status: 'Gentle temperament',
  },
  {
    id: 'food',
    name: 'Balanced Pet Food',
    category: 'Food',
    kind: 'Product',
    price: 'From INR 399',
    age: 'All life stages',
    breed: 'Dogs, cats, birds, fish',
    care: 'Vet-guided nutrition packs with portion suggestions.',
    visual: 'visual-food',
    image: '/images/food.jpg',
    icon: '&#129368;',
    status: 'Best seller',
  },
  {
    id: 'toys',
    name: 'Play & Enrichment Toys',
    category: 'Toys',
    kind: 'Product',
    price: 'From INR 149',
    age: 'All ages',
    breed: 'Multi-pet range',
    care: 'Chew-safe, puzzle, feather, rope, and activity toys.',
    visual: 'visual-toys',
    image: '/images/toys.jpg',
    icon: '&#127922;',
    status: 'New arrivals',
  },
  {
    id: 'accessories',
    name: 'Comfort Accessories',
    category: 'Accessories',
    kind: 'Product',
    price: 'From INR 249',
    age: 'All ages',
    breed: 'Beds, bowls, leashes, tanks',
    care: 'Durable daily essentials selected by our care team.',
    visual: 'visual-accessories',
    image: '/images/accessories.jpg',
    icon: '&#127968;',
    status: 'In stock',
  },
];

export const categoryOptions = {
  dog: [
    {
      id: 'golden-retriever',
      title: 'Golden Retriever',
      subtitle: 'Friendly family companion',
      price: 'Adoption guidance from INR 2,500',
      age: 'Puppy to adult',
      bestFor: 'Active families, first-time pet parents, children',
      traits: ['Gentle', 'Social', 'Trainable'],
      description:
        'Golden Retrievers are warm, intelligent dogs who enjoy human company, regular exercise, and structured play.',
      care:
        'Plan daily walks, weekly brushing, basic obedience practice, and regular ear checks.',
      related: ['Starter leash set', 'High-protein food', 'Grooming package'],
      visual: 'visual-dog',
      icon: '&#128021;',
    },
    {
      id: 'beagle',
      title: 'Beagle',
      subtitle: 'Curious small hound',
      price: 'Adoption guidance from INR 2,200',
      age: 'Young adult',
      bestFor: 'Homes that enjoy walks and scent games',
      traits: ['Playful', 'Food motivated', 'Compact'],
      description:
        'Beagles are cheerful, nose-led companions with a lively personality and a love for puzzle toys.',
      care:
        'Use secure walks, measured meals, scent enrichment, and patient recall training.',
      related: ['Puzzle feeder', 'Harness', 'Training treats'],
      visual: 'visual-dog',
      icon: '&#128021;',
    },
    {
      id: 'indie-dog',
      title: 'Indian Pariah',
      subtitle: 'Smart native breed',
      price: 'Adoption guidance from INR 1,500',
      age: 'All ages',
      bestFor: 'Indian climate, apartments, independent learners',
      traits: ['Hardy', 'Alert', 'Low grooming'],
      description:
        'Indian Pariah dogs are resilient, loyal, and well suited to local weather with thoughtful socialization.',
      care:
        'Focus on social walks, positive training, balanced food, and vaccination routines.',
      related: ['Vaccination plan', 'Cooling mat', 'Daily food pack'],
      visual: 'visual-dog',
      icon: '&#128021;',
    },
  ],
  cat: [
    {
      id: 'persian',
      title: 'Persian Cat',
      subtitle: 'Calm long-hair companion',
      price: 'Adoption guidance from INR 2,000',
      age: 'Kitten to adult',
      bestFor: 'Quiet indoor homes',
      traits: ['Calm', 'Affectionate', 'Grooming needs'],
      description:
        'Persian cats are gentle indoor companions with plush coats and a peaceful daily rhythm.',
      care:
        'Brush frequently, keep eyes clean, use quality litter, and offer soft resting spaces.',
      related: ['Slicker brush', 'Premium litter', 'Cozy bed'],
      visual: 'visual-cat',
      icon: '&#128008;',
    },
    {
      id: 'domestic-short-hair',
      title: 'Domestic Short Hair',
      subtitle: 'Adaptable city cat',
      price: 'Adoption guidance from INR 1,200',
      age: 'All ages',
      bestFor: 'Apartments, busy homes, new cat parents',
      traits: ['Adaptable', 'Low grooming', 'Playful'],
      description:
        'Domestic short hair cats are varied, hardy, and easy to care for with a loving indoor setup.',
      care:
        'Provide scratching posts, litter hygiene, interactive play, and routine vet checks.',
      related: ['Scratch tower', 'Wand toy', 'Litter box kit'],
      visual: 'visual-cat',
      icon: '&#128008;',
    },
    {
      id: 'siamese',
      title: 'Siamese',
      subtitle: 'Talkative social cat',
      price: 'Adoption guidance from INR 2,800',
      age: 'Young adult',
      bestFor: 'People who want an interactive pet',
      traits: ['Vocal', 'Social', 'Smart'],
      description:
        'Siamese cats are expressive, people-focused, and happiest when they have company and mental games.',
      care:
        'Offer climbing space, daily play, puzzle feeders, and a predictable routine.',
      related: ['Cat tree', 'Puzzle feeder', 'Feather toy'],
      visual: 'visual-cat',
      icon: '&#128008;',
    },
  ],
  bird: [
    {
      id: 'budgie',
      title: 'Budgie',
      subtitle: 'Small cheerful companion',
      price: 'From INR 1,200',
      age: 'Young to adult',
      bestFor: 'Beginner bird keepers',
      traits: ['Social', 'Small space', 'Trainable'],
      description:
        'Budgies are bright, social birds that enjoy gentle handling, toys, and a clean cage setup.',
      care:
        'Use a spacious cage, fresh seed mix, leafy greens, and daily supervised interaction.',
      related: ['Starter cage', 'Seed blend', 'Swing toy'],
      visual: 'visual-bird',
      icon: '&#129436;',
    },
    {
      id: 'cockatiel',
      title: 'Cockatiel',
      subtitle: 'Gentle whistling bird',
      price: 'From INR 4,500',
      age: 'Young adult',
      bestFor: 'Homes with daily interaction time',
      traits: ['Gentle', 'Whistling', 'Bonding'],
      description:
        'Cockatiels are affectionate birds known for soft calls, crest expressions, and steady bonding.',
      care:
        'Provide varied perches, pellets, seed treats, bath access, and calm handling.',
      related: ['Pellet diet', 'Natural perches', 'Bath bowl'],
      visual: 'visual-bird',
      icon: '&#129436;',
    },
    {
      id: 'lovebird',
      title: 'Lovebird',
      subtitle: 'Colorful energetic pair',
      price: 'From INR 3,000',
      age: 'Young pair',
      bestFor: 'Experienced keepers or pair setups',
      traits: ['Energetic', 'Colorful', 'Pair friendly'],
      description:
        'Lovebirds bring color and movement, and do best with enrichment, safe toys, and patient handling.',
      care:
        'Use chew-safe toys, fresh vegetables, flight time, and careful socialization.',
      related: ['Chew toys', 'Vegetable clips', 'Flight cage'],
      visual: 'visual-bird',
      icon: '&#129436;',
    },
  ],
  fish: [
    {
      id: 'guppy',
      title: 'Guppy',
      subtitle: 'Colorful starter fish',
      price: 'From INR 150',
      age: 'Young adult',
      bestFor: 'Community tanks and beginners',
      traits: ['Colorful', 'Peaceful', 'Starter friendly'],
      description:
        'Guppies are active, colorful freshwater fish that thrive in peaceful planted aquariums.',
      care:
        'Keep stable water, gentle filtration, weekly checks, and small measured feedings.',
      related: ['Water test kit', 'Micro pellets', 'Aquarium plants'],
      visual: 'visual-fish',
      icon: '&#128032;',
    },
    {
      id: 'betta',
      title: 'Betta',
      subtitle: 'Elegant solo fish',
      price: 'From INR 350',
      age: 'Adult',
      bestFor: 'Single-species display tanks',
      traits: ['Vibrant', 'Solo setup', 'Low current'],
      description:
        'Bettas are striking fish that prefer calm water, warm temperatures, and carefully chosen tank mates.',
      care:
        'Use a heater, low-flow filter, hiding plants, and avoid keeping two males together.',
      related: ['Heater', 'Silk plants', 'Betta food'],
      visual: 'visual-fish',
      icon: '&#128032;',
    },
    {
      id: 'goldfish',
      title: 'Goldfish',
      subtitle: 'Classic cold-water fish',
      price: 'From INR 250',
      age: 'Juvenile',
      bestFor: 'Larger filtered tanks',
      traits: ['Hardy', 'Visible', 'Long lived'],
      description:
        'Goldfish are hardy and charming, but need more space and filtration than many new keepers expect.',
      care:
        'Choose a roomy tank, strong filtration, weekly water changes, and quality sinking food.',
      related: ['Large filter', 'Sinking pellets', 'Gravel cleaner'],
      visual: 'visual-fish',
      icon: '&#128032;',
    },
  ],
  rabbit: [
    {
      id: 'mini-lop',
      title: 'Mini Lop',
      subtitle: 'Soft compact rabbit',
      price: 'Adoption guidance from INR 1,500',
      age: 'Young adult',
      bestFor: 'Indoor homes with floor time',
      traits: ['Gentle', 'Compact', 'Hay focused'],
      description:
        'Mini lops are sweet, soft-eared rabbits who enjoy calm handling and safe indoor play.',
      care:
        'Offer unlimited hay, a roomy pen, soft flooring, nail trims, and supervised exercise.',
      related: ['Timothy hay', 'Exercise pen', 'Ceramic bowl'],
      visual: 'visual-rabbit',
      icon: '&#128007;',
    },
    {
      id: 'dutch-rabbit',
      title: 'Dutch Rabbit',
      subtitle: 'Friendly patterned rabbit',
      price: 'Adoption guidance from INR 1,700',
      age: 'All ages',
      bestFor: 'Families who can supervise gently',
      traits: ['Friendly', 'Curious', 'Neat size'],
      description:
        'Dutch rabbits are alert and personable with a classic pattern and an energetic routine.',
      care:
        'Provide chew toys, hay, leafy greens, litter training, and safe hiding spaces.',
      related: ['Rabbit litter tray', 'Chew sticks', 'Leafy greens pack'],
      visual: 'visual-rabbit',
      icon: '&#128007;',
    },
    {
      id: 'lionhead',
      title: 'Lionhead',
      subtitle: 'Tiny rabbit with a mane',
      price: 'Adoption guidance from INR 2,000',
      age: 'Young adult',
      bestFor: 'Owners ready for coat care',
      traits: ['Small', 'Expressive', 'Grooming needs'],
      description:
        'Lionheads are compact rabbits with distinctive fluffy coats and plenty of personality.',
      care:
        'Brush the mane, keep nails trimmed, maintain hay intake, and prevent heat stress.',
      related: ['Soft brush', 'Cooling mat', 'Hay rack'],
      visual: 'visual-rabbit',
      icon: '&#128007;',
    },
  ],
  food: [
    {
      id: 'dog-cat-kibble',
      title: 'Dog & Cat Kibble',
      subtitle: 'Balanced daily nutrition',
      price: 'From INR 399',
      age: 'Puppy, kitten, adult, senior',
      bestFor: 'Daily complete meals',
      traits: ['Vet guided', 'Portion support', 'Life-stage options'],
      description:
        'Balanced kibble packs support everyday nutrition with protein, fiber, and clear portion guidance.',
      care:
        'Choose by age, size, activity, and sensitivity. Transition gradually over one week.',
      related: ['Measuring scoop', 'Slow feeder', 'Treat pouch'],
      visual: 'visual-food',
      icon: '&#129368;',
    },
    {
      id: 'bird-seed-mix',
      title: 'Bird Seed Mix',
      subtitle: 'Fresh daily blend',
      price: 'From INR 249',
      age: 'Small to medium birds',
      bestFor: 'Budgies, cockatiels, lovebirds',
      traits: ['Fresh', 'Clean blend', 'Easy feeding'],
      description:
        'A clean seed mix for small birds, best paired with greens and mineral support.',
      care:
        'Refresh daily, remove husks, add vegetables, and keep water clean.',
      related: ['Cuttlebone', 'Veg clip', 'Seed cup'],
      visual: 'visual-food',
      icon: '&#129368;',
    },
    {
      id: 'fish-flakes',
      title: 'Fish Flakes & Pellets',
      subtitle: 'Aquarium feeding essentials',
      price: 'From INR 149',
      age: 'Most freshwater fish',
      bestFor: 'Community aquariums',
      traits: ['Easy dose', 'Floating', 'Daily feed'],
      description:
        'Staple flakes and pellets support colorful, active freshwater fish when used in small portions.',
      care:
        'Feed only what fish finish quickly and remove excess to protect water quality.',
      related: ['Auto feeder', 'Water conditioner', 'Test strips'],
      visual: 'visual-food',
      icon: '&#129368;',
    },
  ],
  toys: [
    {
      id: 'chew-toys',
      title: 'Chew Toys',
      subtitle: 'Safe chewing and teething',
      price: 'From INR 149',
      age: 'Puppies and adult dogs',
      bestFor: 'Chewers, teething pets, boredom control',
      traits: ['Durable', 'Chew-safe', 'Washable'],
      description:
        'Chew toys redirect chewing, support dental habits, and keep active pets occupied.',
      care:
        'Match toy size to pet strength and replace when worn or cracked.',
      related: ['Treats', 'Rope toy', 'Dental care kit'],
      visual: 'visual-toys',
      icon: '&#127922;',
    },
    {
      id: 'feather-wands',
      title: 'Feather Wands',
      subtitle: 'Interactive cat play',
      price: 'From INR 199',
      age: 'Cats of all ages',
      bestFor: 'Indoor exercise and hunting play',
      traits: ['Interactive', 'Lightweight', 'Energy burn'],
      description:
        'Feather wands help indoor cats jump, chase, and bond through short play sessions.',
      care:
        'Store after play, rotate toys, and avoid leaving strings unattended.',
      related: ['Scratch post', 'Cat tunnel', 'Treats'],
      visual: 'visual-toys',
      icon: '&#127922;',
    },
    {
      id: 'puzzle-feeders',
      title: 'Puzzle Feeders',
      subtitle: 'Mental enrichment tools',
      price: 'From INR 349',
      age: 'Dogs and cats',
      bestFor: 'Fast eaters and smart pets',
      traits: ['Enrichment', 'Slow feeding', 'Reusable'],
      description:
        'Puzzle feeders turn meals into activity and help pets use their brain while eating slowly.',
      care:
        'Start easy, increase difficulty gradually, and clean after sticky food.',
      related: ['Training treats', 'Slow bowl', 'Clicker'],
      visual: 'visual-toys',
      icon: '&#127922;',
    },
  ],
  accessories: [
    {
      id: 'beds',
      title: 'Beds & Mats',
      subtitle: 'Daily comfort zone',
      price: 'From INR 499',
      age: 'All pets',
      bestFor: 'Rest, crate comfort, senior support',
      traits: ['Soft', 'Washable', 'Size options'],
      description:
        'Comfortable beds give pets a predictable rest space and protect them from hard flooring.',
      care:
        'Choose washable covers, correct size, and place away from strong heat or drafts.',
      related: ['Blanket', 'Cooling mat', 'Calming spray'],
      visual: 'visual-accessories',
      icon: '&#127968;',
    },
    {
      id: 'leashes-harnesses',
      title: 'Leashes & Harnesses',
      subtitle: 'Secure walking gear',
      price: 'From INR 299',
      age: 'Dogs and walk-trained cats',
      bestFor: 'Daily walks and training',
      traits: ['Secure', 'Adjustable', 'Everyday use'],
      description:
        'A well-fitted harness improves control and comfort during walks, training, and travel.',
      care:
        'Measure chest size, check clips often, and avoid loose fits.',
      related: ['ID tag', 'Treat pouch', 'Poop bags'],
      visual: 'visual-accessories',
      icon: '&#127968;',
    },
    {
      id: 'aquarium-kits',
      title: 'Aquarium Kits',
      subtitle: 'Starter tank essentials',
      price: 'From INR 1,499',
      age: 'Freshwater fish setups',
      bestFor: 'New aquarium keepers',
      traits: ['Filtered', 'Starter ready', 'Expandable'],
      description:
        'Starter aquarium kits simplify setup with tank, filter, lighting, and basic care essentials.',
      care:
        'Cycle the tank before adding fish, test water, and avoid overcrowding.',
      related: ['Water conditioner', 'Gravel', 'Plants'],
      visual: 'visual-accessories',
      icon: '&#127968;',
    },
  ],
};

export const services = [
  {
    title: 'Grooming Studio',
    text: 'Bathing, trimming, nail care, coat conditioning, and hygiene packages.',
    icon: '&#9986;',
  },
  {
    title: 'Vet Support',
    text: 'Vaccination guidance, diet review, deworming reminders, and health records.',
    icon: '&#129658;',
  },
  {
    title: 'Boarding',
    text: 'Clean supervised stays with feeding plans, play sessions, and daily updates.',
    icon: '&#127968;',
  },
  {
    title: 'Training',
    text: 'Basic obedience, leash manners, socialization, and home settling support.',
    icon: '&#127891;',
  },
  {
    title: 'Delivery',
    text: 'Same-day delivery for food, toys, litter, aquariums, and care supplies.',
    icon: '&#128666;',
  },
  {
    title: 'Adoption Help',
    text: 'Matching, home checks, starter kits, and post-adoption follow-up calls.',
    icon: '&#128062;',
  },
];

export const trustBadges = [
  'Certified pet care advisors',
  'Vaccination records checked',
  'Clean grooming stations',
  'Transparent adoption process',
];

export const stats = [
  { value: '1.2k+', label: 'Happy adoptions' },
  { value: '4.9/5', label: 'Customer rating' },
  { value: '24/7', label: 'Care support' },
];
